### ISSUE TITLE
Current datetime macro

### ISSUE THREAD

**Issue by Tristan-Stricker** [google/cel-spec#106]
I like that the language is small however I think it would be of great benefit to have a couple of convenience macros for the current datetime. A simple use case that comes to mind would be when writing a security expression that says "the users last login was within the last 30 days" which translated would look like 
`getSeconds(dateTime.UtcNow() - user.lastLogin) <= 30 * 24 * 7 * 60`

Is this out of the question?

**Comment by JimLarson** [comment]
It's not out of the question, but so far the language is deterministic. For the same inputs you always get the same output (up to equivalence, e.g. map field order doesn't matter). This is a property we'd like to preserve.

You can certainly add a `now()` function as an extension function, or even easier, pass in `now` as an ordinary variable.

**Comment by Tristan-Stricker** [comment]
@JimLarson Thanks for the reply & explanation.

Closing as designed.
