### ISSUE TITLE
More Descriptive Missing Attribute Error Message

### ISSUE THREAD

**Issue by mtheodorides** [google/cel-spec#112]
The current error message for missing attributes looks like this: "no such attribute: &{2 [0xc00039f030] 0xc000196cb0 0xc000196cb0 0xc000dac540}"

It would be nice if the message made it easier for humans to identify the attribute that is missing by including a variable name in the message.

**Comment by TristonianJones** [comment]
Thanks for the report. Since the same issue has been reported as https://github.com/google/cel-go/issues/330, I'm going to close this as a duplicate.
