### ISSUE TITLE
Can you have any (interactive/simple/easy) tutorial for newcomer? 

### ISSUE THREAD

**Issue by MeisterVenom** [google/cel-spec#121]
**cel** looks great, and backed by Google. But it seems so tough to adapt it and even kick off.

It'd be really great if Google can provide a tutorial for starter like me. Many thanks!

**Comment by TristonianJones** [comment]
The CEL-Go codelab was just published! There are a couple minor doc fixes, but please feel free to give it a look.
https://codelabs.developers.google.com/codelabs/cel-go/#0
https://github.com/google/cel-go/pull/328
