### ISSUE TITLE
Add notation and/or constructors for durations in days, hours, or minutes

### ISSUE THREAD

**Issue by JimLarson** [google/cel-spec#138]
The current duration constructor takes only a decimal string with a number of seconds, e.g. `duration("5184000s")`. There is desire for more handy units, e.g. `duration("60d")`. (Assuming we ignore leap seconds.)

The underlying protobuf well-known type goes down to nanoseconds, so we could potentially have "ms", "µs", and "ns" too.

A week is unambiguous, but month, quarter, year, etc. seem error-prone.

We could go full ISO 8601 and allow durations like "2h30m45s", but it's easy enough to compose them with addition: `duration("2h") + duration("30m") + duration("45s")`, although it's clunkier.

We could alternatively have separate constructors, e.g. `hours(7)`, maybe in an extension library.

**Comment by slott56** [comment]
Are these normalized in any way when a duration is the output from the expression? Would a trivial expression like `duration("2h30m45s")` output `duration("8454s")`?  Would we need timestamp-like extractor methods? `int(duration("8454s").hours()) == 2`?

**Comment by jsannemo** [comment]
This would be very nice to have, and the option of `duration("2h30m45s") over adding each unit separately seems nicer. Both cel-go and cel-cpp supports this, so one might just as well formalize it. 

Also, I believe fractional seconds are allowed in both cel-go and cel-cpp (cel-cpp seems to use absl::ParseDuration which afaict is essentially the same logic as `time.ParseDuration`), but it is not clear that this is the case in the spec.

**Comment by JimLarson** [comment]
The go syntax seems like a reasonable standard to follow. There doesn't seem to be a standard duration notation in Google SQL or Javascript - the prototype languages we try to follow. There's an ISO-8601 notation for durations, but it's clunky and and not compatible with the current "120s" notation.

**Comment by TristonianJones** [comment]
A common subset of the duration parsing syntax supported by Go (native), Java ([threeten-extra](https://github.com/ThreeTen/threeten-extra/pull/182)), and C++ (abseil.io) has been introduced in all of the runtimes, and the spec now clarifies the supported notation and character set.  Days is not supported, but more granular units are. See https://github.com/google/cel-spec/issues/185
