### ISSUE TITLE
governance.md references private/non-existent mailing list

### ISSUE THREAD

**Issue by kapilt** [google/cel-spec#140]
the governance markdown doc references cel-lang-discuss@googlegroups.com which afaics is not a public group (or is non-existent). The cel-go-discuss group does exist and seems to be the only public mailing list for questions. If the cel-lang-discuss group exists, then the request would be to make it public so others can participate/learn. If it doesn't exist then the governance doc should be updated to reflect the mailing list in use, or another mailing should be created.

**Comment by TristonianJones** [comment]
Hi @kapilt the group is public, anyone can view and anyone can join, but only members may post. Could you let me know if this link works for you? https://groups.google.com/g/cel-lang-discuss

**Comment by TristonianJones** [comment]
Please feel free to re-open the issue if you have any trouble with joining the group. We'd be happy to have you!
