### ISSUE TITLE
Support an easier to use duration string

### ISSUE THREAD

**Issue by TristonianJones** [google/cel-spec#185]
Currently, the cel-spec indicates that the duration string format accepted within protobuf libraries is what CEL can consume; however, this means that the only valid duration unit is 's' for seconds. A more human-readable format that understands inputs at the granularity of hours, minutes, and seconds would be a vast improvement.

**Comment by jcking** [comment]
We should probably push for protobuf to accept the new units as well. I would suggest the following.

```
"1d" -> google.protobuf.Duration{
  seconds: 86400
}
"1h" -> google.protobuf.Duration{
  seconds: 3600
}
"1m" -> google.protobuf.Duration{
  seconds: 60
}
"1s" -> google.protobuf.Duration{
  seconds: 1
}
"1ms" -> google.protobuf.Duration{
  nanos: 1000000
}
"1us" -> google.protobuf.Duration{
  nanos: 1000
}
"1ns" -> google.protobuf.Duration{
  nanos: 1
}
```

**Comment by TristonianJones** [comment]
@jcking I think up to the hour level is about as far as we could reasonably support, but yes, I would love it if proto could support more than just the 's' suffix.
