### ISSUE TITLE
Extract function

### ISSUE THREAD

**Issue by michalstefanext** [google/cel-spec#222]
I am not able to find/figure out, how to use "extract" function (https://cloud.google.com/iam/docs/conditions-attribute-reference#extract). Would you be able to provide some small example or give me some direction at least please? Right now, whatever I try, I always get:

Exception in thread "main" org.projectnessie.cel.tools.ScriptCreateException: check failed: ERROR: <input>:1:22: undeclared reference to 'extract' (in container '')

for this:
Script script = scriptHost.buildScript("assertion.arn.extract('{account_arn}/assumed-role')")

I simply am unable to find out, how to define the identifier (account_arn) of extract method.

Thanks!

**Comment by liubog2008** [comment]
how about this problem? @michalstefanext
