### ISSUE TITLE
Is the cel-spec compatible with Kotlin, if so, how do I add this in my project? 

### ISSUE THREAD

**Issue by AarshShah33** [google/cel-spec#236]

**Comment by TristonianJones** [comment]
@AarshShah33 at this time there is not a Kotlin specific implementation of CEL, though there is one in Java which you might consider using: https://github.com/projectnessie/cel-java

**Comment by CLOVIS-AI** [comment]
I have started development on a Kotlin implementation, but it's far from being usable. https://gitlab.com/opensavvy/cel
