### ISSUE TITLE
Merging maps

### ISSUE THREAD

**Issue by alexec** [google/cel-spec#245]
Consider this CeL expression:

```js
    {
      "specversion": "1.0",
      "source": "intuit",
      "id": event.source+"/"+event.id,
      "type": event.type,
      "subject": has(event.subject) ? event.subject : "",
      "intuitaccountid": has(event.intuitaccountid) ? event.intuitaccountid : "",
      "datacontentype": "application/json",
      "data": event.data
    }
```

You'll see that it maps an input event to an output event (CloudEvent to be specific). 

Some of the fields in the input event are optional and may not exist. Because CeL does not have a nill value, I insert empty strings. But really, I want those missing input fields to also be missing output fields. Essentially, I think I want to merge maps.

```js
    merge({
      "specversion": "1.0",
      "source": "intuit",
      "id": event.source+"/"+event.id,
      "type": event.type,
      "datacontentype": "application/json",
      "data": event.data
    },  
    has(event.subject) ? {"subject": event.subject} : {}, 
    has(event.intuitaccoutid) ? {"intuitaccountid": event.intuitaccountid} : {}
     )
```

**Comment by TristonianJones** [comment]
@alexec I have a design forthcoming for optional values as a canonical extension of CEL. Give me a bit of time to put together the design doc in wiki form, but you can expect to see development in this direction in both the cel-go and cel-cpp repos. 

The exact syntax will look as follows:

```
{
      "specversion": "1.0",
      "source": "intuit",
      "id": event.source+"/"+event.id,
      "type": event.type,
      "datacontentype": "application/json",
      "data": event.data,
       ?"subject": event.?subject,
       ?"intuitaccountid": event.?intiuitaccountid,
}
```

**Comment by TristonianJones** [comment]
I'm going to close this issue for now since it should be captured in #246 with the details present in https://github.com/google/cel-spec/wiki/proposal-246
