### ISSUE TITLE
Map to Map/List conversion

### ISSUE THREAD

**Issue by zhqu1148980644** [google/cel-spec#248]
The spec says `map/filter` macro only support `list` type, how to apply `map/filter` macros to map, so we can transform a map to another map or list.

expected use case:
1. map to list
```
{
  "k1": "v1",
  "k2": "v2"
}.map({k, v}, {k: v})

==>

[
 {"k1": "v1"},
 {"k2": "v2"}
]
```

2. list to map
```
map([
["k1", "v1"],
["k2": "v2"]
])

==>
{
  "k1": "v1",
  "k2": "v2"
}

```

**Comment by matthchr** [comment]
I'm also curious about this.

**Comment by TristonianJones** [comment]
Hi All, we've been working on supporting two-variable comprehensions to support this case. It's currently available in the Go and C++ stacks. 

See the cel-go ext/README.md for more details
https://github.com/google/cel-go/tree/master/ext

**Comment by kfox1111** [comment]
Something the k8s folks support / would be willing to support?
