### ISSUE TITLE
has() macro for complicated map key

### ISSUE THREAD

**Issue by papazloynt** [google/cel-spec#268]
Hi evereyone!
Is it possible to use has() macro for map's keys with dots f.e. : ```"ECS.Host.Name"```.
When i use template like this: "has(events["ECS.Host.Name"])" i got error like this: 
``` 
"ERROR: <input>:1:4: invalid argument to has() macro
 | has(events["ECS.Host.Name"]) && events["ECS.Host.Name"] == "myName"
 | ...^"
```

**Comment by TristonianJones** [comment]
@papazloynt for complex map keys, prefer the `in` syntax: `"ECS.Host.Name" in events`.

-Tristan
