### ISSUE TITLE
Separate implementation-private builtins and identifier namespaces.

### ISSUE THREAD

**Issue by JimLarson** [google/cel-spec#30]
In the CEL implementations, operator expressions like "a + b" are parsed to become function calls like "\_+\_"(a, b), for a function named "\_+\_".  This does not conflict with the namespace of functions that users can add to the CEL evaluator, since "\_+\_" is not a valid identifier.  However, we have private builtins in the implementations for "\_in\_", and soon to have "\_not_strictly_false\_".  These *are* valid identifiers and trespass into the space that should be reserved for user extensions of CEL.

We should either:
A) Change "\_in\_" and "\_not_strictly_false\_" to have some gratuitous punctuation to make them invalid as identifiers, or
B) Change the definition of identifiers to disallow a leading underscore.

**Comment by TristonianJones** [comment]
This has been fixed within the cel-go repository by using the `@<function>` name convention for human-readable operators.
