### ISSUE TITLE
Checking for undeclared reference

### ISSUE THREAD

**Issue by shmul** [google/cel-spec#328]
Hi,
is there a way to check for an undeclared reference? Something similar to `has(e)` where `e` is just a variable that may have not been declared?

Cheers,
Shmul

**Comment by TristonianJones** [comment]
The best way to approach this would be to use optional values if you're using Java or Go:
https://github.com/google/cel-spec/wiki/proposal-246

```
// assumes e is declared as an optional_type(T) 
// where T is the desired type if provided.
e.hasValue()
```

This feature is coming soon for C++
