### ISSUE TITLE
What does the `~*` mean?

### ISSUE THREAD

**Issue by gnclmorais** [google/cel-spec#343]
I’m looking to port CEL into a [Lezer perser](https://lezer.codemirror.net) but I’m struggling to understand something on the lexis:
```
STRING_LIT     ::= [rR]? ( "    ~( " | NEWLINE )*  "
                         | '    ~( ' | NEWLINE )*  '
                         | """  ~"""*              """
                         | '''  ~'''*              '''
                         )
```

What does the tilde-asterisk (`~XXX*`) combo mean?

**Comment by jnthntatum** [comment]
It means negation (so include anything up until the closing """ for a multiline string in that case).
