### ISSUE TITLE
Is there a Java implementation?

### ISSUE THREAD

**Issue by tomsheep** [google/cel-spec#36]

**Comment by TristonianJones** [comment]
Hi Tom, it's possible to create a Java implementation. If there's significant interest, this is something we could add to our backlog. It would likely surface at github.com/google/cel-java rather than within cel-spec.

**Comment by dburl** [comment]
Hi, are there still plans to have CEL-java? 
The provided link `github.com/google/cel-java` is not operational.

**Comment by mustafaakin** [comment]
It seems it's available now: https://github.com/google/cel-java not tested though.
