### ISSUE TITLE
Unable to build using bazel 

### ISSUE THREAD

**Issue by jorge-ferrero-ag** [google/cel-spec#390]
**cel.dev/expr v0.16.1**

ERROR: no such package '@@com_google_googleapis//google/rpc': The repository '@@com_google_googleapis' could not be resolved: Repository '@@com_google_googleapis' is not defined
ERROR: /private/var/tmp/_bazel_***l/83a47d44f44a6f65298c8007f097ac39/external/dev_cel_expr/proto/cel/expr/BUILD.bazel:127:17: no such package '@@com_google_googleapis//google/rpc': The repository '@@com_google_googleapis' could not be resolved: Repository '@@com_google_googleapis' is not defined and referenced by '@@dev_cel_expr//proto/cel/expr:google_rpc_status_go_proto'

Im getting this error trying to build using bazel. Please, could someone help me with this ?

**Comment by TristonianJones** [comment]
@jorge-ferrero-ag I'm not able to reproduce the build error. Have you tried performing a `bazel clean --expunge` before building?

**Comment by dansheerhealth** [comment]
We're also seeing this one. `bazel clean --expunge` still results in the same. This was after an upgrade to the spanner go libraries brought in this dep transitively in a bzlmod enabled workspace.

**Comment by TristonianJones** [comment]
@dansheerhealth could you provide a link to the Spanner go library? It could be due to minimum version selection between projects.

**Comment by jorge-ferrero-ag** [comment]
From mi side, im using cloud.google.com/go/spanner v1.67.0. After running `go mod tidy` the **cel.dev/expr** has been included in my go.mod using v0.15.0.

**Comment by jorge-ferrero-ag** [comment]
I've tried to bump the cel.dev/expr to v0.16.1 but bazel is throwing the error that i've reported at the very beginning of the issue.

**Comment by TristonianJones** [comment]
@jorge-ferrero-ag @dansheerhealth It's possible that the `google.rpc.Status` proto is being resolved oddly due to a BUILD rule within cel-spec. I'm going to try to remove what I think is the problematic BUILD rule to see if it addresses the issue.

**Comment by dansheerhealth** [comment]
@TristonianJones 

Got a good build after upgrading to that commit, thank you!

> v0.16.2-0.20240918031708-aa697b0f2510

**Comment by jorge-ferrero-ag** [comment]
@TristonianJones thanks for taking care of it! 😃 

are you going to release a new version including this fix ? 🚀

**Comment by TristonianJones** [comment]
I just released a new version. Thanks for both of your help!
