### ISSUE TITLE
Incorrect example in documents.

### ISSUE THREAD

**Issue by 1BADragon** [google/cel-spec#396]
I believe an example for `getDayOfMonth` is incorrect.

The example is this one:
```
timestamp("2023-12-25T12:00:00Z").getDayOfMonth("America/Los_Angeles") // 23
```

I'm pretty sure this time adjusted to LA is actually 0400 of the 25th still. So the answer should stay 24. Should it not? 

Thanks in advance.

**Comment by TristonianJones** [comment]
You're quite right, I think the example was supposed to be `00:00:00`
