### ISSUE TITLE
Clarify whether regexp matching is full- or sub-string

### ISSUE THREAD

**Issue by JimLarson** [google/cel-spec#73]
Preference is for substring matching: otherwise ^ and $ are useless.

Either mode can express the other semantics:  ^pattern$ vs .*pattern.*

Also consider adding another method for full-string matching:  matchesAll()?

**Comment by TristonianJones** [comment]
I believe both C++ and Go implement substring matching and makes use of `^` and `$` to allow users to specify full, prefix, or suffix matching as needed.

**Comment by JimLarson** [comment]
Closed by PR #92
